### ISSUE TITLE
Persisting data from Atlas

### ISSUE THREAD

**Issue by davidpr** [lucasmsp/docker-atlas#6]
Hi, I'm looking into the docker-compose and I see there's one volume mounted: 

 volumes:
      - ./atlas/resources/1000-Hadoop:/opt/atlas/models/1000-Hadoop

This is for the example of having some models already loaded. However, I'm interested in having a stateful installation where I can do docker-compose up and ctrl+c and then doing docker-compose up again and having in Atlas all defined Types and loaded entities. Do you know what volumes should be required to make the installation stateful ?

Thanks,
David

**Comment by lucasmsp** [comment]
Hi, the resources at 1000-Hadoop is only the entity's template that you may want to add in Atlas to be able to audit big data tools. It's not contains data! In other words, these templates are used to make Atlas understand the content sent by big data tools. Data is added in Atlas by using Hooks when using tools that support it. 

The volume path in the docker-compose file is a volume expose, which means that you can use this path to share files between the container and host, but it's also can be used to save the state of some contents in the host. Making Atlas fully stateful may be hard because it depends on Zookeper and Kafka. But depending on your needs, this may be achieved by persisting directories like  /opt/atlas/conf/, /opt/atlas/log/ and /opt/atlas/data/

**Comment by davidpr** [comment]
got it Lucas, thanks a lot. I don't mind loosing the metadata events that are going to be recorded in Atlas (that are in Kafka topics to be ingested still for example), but at least what's already ingested as metadata, lets say all the entities and the defined types should be retrievable. I'll try looking at those /opt directories.

**Comment by davidpr** [comment]
Hi @lucasmsp, I have tried creating a Type and and Identity and then doing Ctrl+C and restarting the deployment by doing docker-compose up again and I find the defined Type and Identity are still in there in the search results. How it is possible that they are there if the docker-compose only mounts the volume for the 1000-Hadoop folder? is there any configuration that is persisting the HBase data somehow or docker-compose doing some persistence?

**Comment by lucasmsp** [comment]
Hi @davidpr, by default, docker keeps their containers after existing them (that's why you need to use `docker rm` to make sure that docker will remove it at the end). In case of using docker-compose, I suggest to check this [page](https://docs.docker.com/engine/reference/commandline/compose_rm/), the command `docker-compose rm -fsv`  may help you.

**Comment by davidpr** [comment]
got it. Thanks @lucasmsp
